// 리그 메타데이터. CSV의 League 컬럼 값과 leagueName이 정확히 일치해야 매칭됩니다.
// 6개월마다 CSV를 새로 받으면 이 파일은 보통 손댈 필요가 없습니다.
// 다만 팀 수가 채워지거나 리그 구성이 바뀌면 note/expectedTeams를 업데이트하세요.
const LEAGUES = [
  {
    id: "premier-league",
    leagueName: "Premier League",
    displayName: "프리미어리그",
    country: "England",
    file: "data/premier_league_players.csv",
    expectedTeams: 20,
  },
  {
    id: "championship",
    leagueName: "English Championship",
    displayName: "챔피언십",
    country: "England",
    file: "data/championship_players.csv",
    expectedTeams: 24,
    note: "4개 팀 데이터가 누락되어 있습니다.",
  },
  {
    id: "la-liga",
    leagueName: "La Liga",
    displayName: "라리가",
    country: "Spain",
    file: "data/la_liga_players.csv",
    expectedTeams: 20,
    note: "5개 팀 데이터가 누락되어 있습니다 (확인 필요).",
  },
  {
    id: "segunda-division",
    leagueName: "Segunda División",
    displayName: "세군다 디비시온",
    country: "Spain",
    file: "data/segundadivision_players.csv",
    expectedTeams: 22,
  },
  {
    id: "bundesliga",
    leagueName: "Bundesliga",
    displayName: "분데스리가",
    country: "Germany",
    file: "data/bundesliga_players.csv",
    expectedTeams: 18,
  },
  {
    id: "2-bundesliga",
    leagueName: "2. Bundesliga",
    displayName: "2.분데스리가",
    country: "Germany",
    file: "data/zweitebundesliga_players.csv",
    expectedTeams: 18,
  },
  {
    id: "serie-a",
    leagueName: "Serie A",
    displayName: "세리에 A",
    country: "Italy",
    file: "data/seriea_players.csv",
    expectedTeams: 20,
  },
  {
    id: "ligue-1",
    leagueName: "Ligue 1",
    displayName: "리그앙",
    country: "France",
    file: "data/ligue1_players.csv",
    expectedTeams: 18,
  },
  {
    id: "eredivisie",
    leagueName: "Eredivisie",
    displayName: "에레디비지에",
    country: "Netherlands",
    file: "data/eredivisie_players.csv",
    expectedTeams: 18,
  },
  {
    id: "primeira-liga",
    leagueName: "Primeira Liga",
    displayName: "프리메이라리가",
    country: "Portugal",
    file: "data/primeiraliga_players.csv",
    expectedTeams: 18,
  },
  {
    id: "mls",
    leagueName: "MLS",
    displayName: "MLS",
    country: "USA/Canada",
    file: "data/mls_players.csv",
    expectedTeams: 30,
  },
  {
    id: "saudi-pro-league",
    leagueName: "Saudi Pro League",
    displayName: "사우디 프로리그",
    country: "Saudi Arabia",
    file: "data/saudiproleague_players.csv",
    expectedTeams: 18,
  },
  {
    id: "k-league-1",
    leagueName: "K League 1",
    displayName: "K리그1",
    country: "South Korea",
    file: "data/kleague1_players.csv",
    expectedTeams: 12,
    note: "4개 팀 데이터가 누락되어 있고, 시즌 기록(출장/득점 등)이 없어 기본 정보만 제공됩니다.",
    noStats: true,
  },
];

// 국가 코드 (ISO 3166-1 alpha-2) → 국기 이모지 매핑에 쓰기 위한 국가명 정규화
const NATIONALITY_TO_ISO = {
  Albania: "AL", Algeria: "DZ", Andorra: "AD", Angola: "AO", Argentina: "AR",
  Armenia: "AM", Australia: "AU", Austria: "AT", Belarus: "BY", Belgium: "BE",
  Bermuda: "BM", Bolivia: "BO", "Bosnia and Herzegovina": "BA", Brazil: "BR",
  Bulgaria: "BG", "Burkina Faso": "BF", Burundi: "BI", Cameroon: "CM",
  Canada: "CA", "Cape Verde Islands": "CV", "Central African Republic": "CF",
  Chad: "TD", Chile: "CL", Colombia: "CO", "Comoros Islands": "KM",
  Congo: "CG", "Congo DR": "CD", "Costa Rica": "CR", Croatia: "HR",
  Curaçao: "CW", Cyprus: "CY", Czechia: "CZ", Denmark: "DK",
  "Dominican Republic": "DO", Ecuador: "EC", Egypt: "EG", "El Salvador": "SV",
  England: "GB-ENG", "Equatorial Guinea": "GQ", Estonia: "EE",
  "Faroe Islands": "FO", Finland: "FI", France: "FR", "French Guiana": "GF",
  Gabon: "GA", Gambia: "GM", Georgia: "GE", Germany: "DE", Ghana: "GH",
  Greece: "GR", Grenada: "GD", Guadeloupe: "GP", Guatemala: "GT",
  Guinea: "GN", "Guinea-Bissau": "GW", Haiti: "HT", Honduras: "HN",
  Hungary: "HU", Iceland: "IS", Indonesia: "ID", Iran: "IR", Iraq: "IQ",
  Israel: "IL", Italy: "IT", "Ivory Coast": "CI", Jamaica: "JM", Japan: "JP",
  Jordan: "JO", Kenya: "KE", Kosovo: "XK", Latvia: "LV", Libya: "LY",
  Lithuania: "LT", Luxembourg: "LU", Madagascar: "MG", Malawi: "MW",
  Malaysia: "MY", Mali: "ML", Martinique: "MQ", Mauritania: "MR",
  Mexico: "MX", Moldova: "MD", Montenegro: "ME", Morocco: "MA",
  Mozambique: "MZ", Netherlands: "NL", "New Caledonia": "NC",
  "New Zealand": "NZ", Niger: "NE", Nigeria: "NG", "Northern Ireland": "GB-NIR",
  Norway: "NO", Panama: "PA", Paraguay: "PY", Peru: "PE",
  Philippines: "PH", Poland: "PL", Portugal: "PT", "Puerto Rico": "PR",
  "Republic of Ireland": "IE", Romania: "RO", Russia: "RU",
  "Saudi Arabia": "SA", Scotland: "GB-SCT", Senegal: "SN", Serbia: "RS",
  "Sierra Leone": "SL", Slovakia: "SK", Slovenia: "SI", "South Africa": "ZA",
  "South Korea": "KR", Spain: "ES", "St Lucia": "LC", Suriname: "SR",
  Sweden: "SE", Switzerland: "CH", Syria: "SY", Thailand: "TH", Togo: "TG",
  "Trinidad and Tobago": "TT", Tunisia: "TN", "Türkiye": "TR", USA: "US",
  Uganda: "UG", Ukraine: "UA", "United Arab Emirates": "AE", Uruguay: "UY",
  Uzbekistan: "UZ", Venezuela: "VE", Wales: "GB-WLS", Yemen: "YE",
  Zambia: "ZM", Zimbabwe: "ZW",
};

const POSITION_LABELS = {
  G: "골키퍼",
  D: "수비수",
  M: "미드필더",
  F: "공격수",
};
